apiVersion: v1
kind: Pod
metadata:
  name: podrick
  namespace: workloads
spec:
  containers:
    - name: centos
      image: docker.io/centos:7
      command: ["/bin/sleep"]
      args: [ "3600" ]
      volumeMounts:
        - mountPath: /mnt/data
          name: podrick-data
  volumes:
    - name: podrick-data
      persistentVolumeClaim:
        claimName: podrick-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podrick-data
  namespace: workloads
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: csi-vxflexos.dellemc.com
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: pfx03-platinum
  volumeMode: Filesystem

