apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: openshift-nmstate
    name: openshift-nmstate
  name: openshift-namestate
    annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  finalizers:
  - kubernetes
