apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: NMState.v1.nmstate.io
  name: openshift-nmstate
  namespace: openshift-nmstate
  annotations:
    argocd.arogproj.io/sync-wave: "0"
spec:
  targetNamespaces:
  - openshift-nmstate
