apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: nmstate-subscription
  namespace: openshift-nmstate  # Install namespace for the operator
spec:
  channel: stable
  name: nmstate
  source: redhat-operators  # For OpenShift. Use 'community-operators' for Kubernetes
  sourceNamespace: openshift-marketplace
