apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pfx03-platinum
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi-vxflexos.dellemc.com
reclaimPolicy: Delete
allowVolumeExpansion: true
parameters:
   storagepool: SP01
   systemID: 49fe0043621c8a0f
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: csi-vxflexos.dellemc.com/49fe0043621c8a0f
    values:
    - csi-vxflexos.dellemc.com
