apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: dell-csm-operator-certified
  namespace: dell-csm-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: dell-csm-operator-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: dell-csm-operator-certified.v1.6.0
