apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cert-manager-subscription
  namespace: cert-manager-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: stable
  name: cert-manager
  source: certified-operators
  sourceNamespace: openshift-marketplace
